package com.cariochi.objecto;

import java.lang.annotation.Retention;
import java.lang.annotation.Target;

import static java.lang.annotation.ElementType.METHOD;
import static java.lang.annotation.RetentionPolicy.RUNTIME;

/**
 * Defines a custom generator for a field of a generated type.
 * <p>
 * The {@link #type()} attribute identifies the owner type, and {@link #field()} identifies the field path
 * or method-call expression to populate.
 *
 * <pre>{@code
 * interface IssueFactory {
 *
 *     @FieldGenerator(type = Issue.class, field = "key")
 *     default String issueKey(ObjectoRandom random) {
 *         return "ID-" + random.nextInt(1000, 10_000);
 *     }
 * }
 * }</pre>
 *
 * <p>
 * Field paths can be nested, for example {@code "properties.value"}. Setter-like expressions such as
 * {@code "properties.setSize(?)"} are also supported.
 */
@Target(METHOD)
@Retention(RUNTIME)
public @interface FieldGenerator {

    /**
     * Owner type whose field should be generated by the annotated method.
     *
     * @return generated object type that owns the field
     */
    Class<?> type();

    /**
     * Field path or method-call expression to populate.
     *
     * @return field path, for example {@code "key"} or {@code "properties.value"}
     */
    String field();

}
